tap "d12frosted/emacs-plus"

cask "font-fira-code-nerd-font"
cask "font-fira-sans"
# font-noto-emoji was renamed to font-noto-color-emoji in Homebrew
cask "font-noto-color-emoji"
cask "font-noto-sans-symbols-2"

cask "wezterm"
cask "nikitabobko/tap/aerospace"
cask "zed"
cask "dbeaver-community"
cask "karabiner-elements"
cask "hammerspoon"

brew "gcc"
brew "libgccjit"
brew "emacs-plus@30", args: ["with-native-comp"]
brew "jpeg"
brew "zlib"
brew "tree-sitter@0.25"
brew "git"
brew "ripgrep"
brew "fd"
brew "prettier"
brew "cake"
brew "coreutils"
brew "libtool"
brew "texinfo"
brew "direnv"
brew "rbenv"
brew "shellcheck"
brew "editorconfig"
brew "eza"
brew "starship"
brew "ispell"
brew "jq"
brew "colima"
brew "docker"
brew "docker-buildx"
brew "protobuf"
brew "cpulimit"
brew "oci-cli"
brew "kubectl"
brew "d2"
brew "libnice"
brew "boost"
brew "pass"
brew "gibo"
brew "leveldb"
brew "stylelint"
brew "js-beautify"
brew "pandoc"
brew "shfmt"
brew "redpanda-data/tap/redpanda"
